language: java
before_install:
  - git clone https://github.com/DevelopmentOnTheEdge/xmltest.git
    && cd xmltest
    && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    && cd ../
  - git clone https://github.com/DevelopmentOnTheEdge/beanexplorer.git
    && cd beanexplorer
    && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    && cd ../
  - git clone https://github.com/DevelopmentOnTheEdge/be-sql.git
    && cd be-sql
    && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    && cd ../
  - git clone https://github.com/DevelopmentOnTheEdge/be5.git
    && cd be5
    && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    && cd ../
install:
  - mvn test-compile -Dmaven.javadoc.skip=true -B -V
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  email: false
