testBe5app:
  features:
  - beSqlQueries
  - eventDbLogging
  - documentCategories
  - logging
  l10n: ru
  projectFileStructure: {}
  modules:
  - core:
      entities: []
  application:
  - _welcome_
  - testtable
  scripts:
  - Post-db
  - dictionaries
