testBe5app:
  features: logging
  l10n: ru
  projectFileStructure: {}
  modules:
  - core:
      entities: []
  - system:
      entities: []
  application:
  - _welcome_
  - testtable
  scripts:
  - Post-db
  - dictionaries
