${artifactId}:
  projectFileStructure:
    groovyQueriesDir: src/main/groovy
    groovyOperationsDir: src/main/groovy
    groovyExtendersDir: src/main/groovy
  features:
  - beSqlQueries
  #- eventDbLogging
  #- compiledGroovy
  l10n: [en,ru]
  modules:
  - core:
      entities: []
  application:
  - _welcome_
  - testtable
  scripts:
  - Post-db
  - dictionaries


